### ISSUE TITLE
Ration 16:9 pas affiché

### ISSUE THREAD

**Issue by 73VW** [HE-Arc/slides-devweb#17]
https://github.com/HE-Arc/slides-devweb/blob/76cbc592a69a002ea71b92b46a1334138bd41d5b/templates/header.html

Le style 16:9 définit dans le fichier ci-dessus ne sert malheureusement pas à grand chose car Dzslides l'override en fin de fichier avec son propre style:
https://github.com/HE-Arc/slides-devweb/blob/gh-pages/00-presentation.html#L557-L562

Je sais pas si ce ratio est une nécessité ou pas, mais sinon on peut peut-être trouver une option pour avoir les deux ratios.

**Comment by grunenwald** [comment]
Sûr ? Vous avez testé en le dé-commentant ? 
Je l'avais commenté l'année passée parce que tous les beamers de l'école ont des res natives 4/3. Mais avant le commentaire j'avais bien du 16/9. J'attends maintenant que l'école change ses beamers, c'est ma seule motivation de changer le ratio.

**Comment by 73VW** [comment]
@grunenwald en ayant enregistré le fichier en local ça fonctionne en fait oui. Mais avec les outils développeurs intégrés au navigateur ça voulait pas, le texte restait aligné au format 4:3. Au temps pour moi.

Par contre je maintiens la proposition d'essayer de trouver une solution pour avoir les deux du coup.

**Comment by grunenwald** [comment]
Si vous avez rien de mieux à faire, volontiers. Mais ce n'est pas une priorité de mon côté

**Comment by 73VW** [comment]
Comme pour le style, je le ferai si j'ai le temps.
