### ISSUE TITLE
Migrate to Travis-CI.com

### ISSUE THREAD

**Issue by greut** [HE-Arc/slides-devweb#45]
> we are announcing that travis-ci.org will be officially closed down completely on December 31st, 2020
>
> https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by greut** [comment]
done, https://travis-ci.com/github/HE-Arc/slides-devweb

the badge in the readme needs to be updated though.

**Comment by grunenwald** [comment]
Thx ! I updated the badge and it seems to work...

**Comment by greut** [comment]
Closed by c80977a14a4585052f7095a7ba14f3902263d04a

Perfect!
